name=LibR200
version=1.0.0
author=Fco. Javier Rodriguez Navarro
maintainer=Javier <webmaster@pinguytaz.net>
sentence=Clase lector R200 de tarjetas RFID-UHF
paragraph= Gestion del lector IN-R200 de tarjetas RFID-UHF
category=Device Control
url=https://github.com/pinguytaz/LibreriasArduino/tree/main/LibR200
architectures=arduino,esp32
